### ISSUE TITLE
Where is the love??

### ISSUE THREAD

**Issue by millermk1717** [fm6000/CPUtempAlert#1]
I'm somewhat new to github and just wanted to comment on this project, but I spent a long time looking for an auto-alerting temperature monitor solution that wasn't a full-blown heavier system monitor with an extensive menu bar / application GUIs.

And this project is perfect! 

I'm sorry I have only one star to give but this project deserves way more kudos/attention. (Im installing at the moment, so that is presuming it does what it says haha.) But thank you so much!

**Comment by fm6000** [comment]
Thanks a lot for your feedback! This APP was really made base on feelings like yours. Please let me know your suggestions later on.
